allianz_dbt_assignment:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: TPRJBGM-UH01600
      user: VIJAYPALANISAMY
      password: w}2f#-3pDZbkr2JN
      role: ACCOUNTADMIN
      database: allianz
      schema: ""
      warehouse: COMPUTE_WH
      threads: 10
      client_session_keep_alive: False
      query_tag: dbt

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: False # default: false